import {
    IsDateString,
    IsEnum,
    IsNumber,
    IsString,
    Min,
    ValidateIf,
} from 'class-validator';
import { SavingsCurrency, SavingsStorage } from './savings.dto';

export enum TransactionType {
    EXPENSE = 'expense',
    INCOME = 'income',
}

export class TransactionDto {
    @IsEnum(TransactionType)
    transactionType: TransactionType;
    @IsString()
    id: string;
    @IsNumber()
    @Min(0.01)
    value: number;
    @IsDateString()
    date: Date;
    @IsString()
    categorie: string;
    @IsString()
    description: string;

    @ValidateIf(
        (transaction: TransactionDto) =>
            transaction.transactionType === TransactionType.EXPENSE &&
            transaction.categorie === 'savings',
    )
    @IsEnum(SavingsStorage)
    savingsStorage?: SavingsStorage;

    @ValidateIf(
        (transaction: TransactionDto) =>
            transaction.transactionType === TransactionType.EXPENSE &&
            transaction.categorie === 'savings',
    )
    @IsEnum(SavingsCurrency)
    savingsCurrency?: SavingsCurrency;

    /** Generated by the server. It is intentionally not accepted from API input. */
    savingsOperationId?: string;
}
